wandb_version: 1

CLI-command:
  desc: null
  value: train.py --model rnn
CUDA_VISIBLE_DEVICES:
  desc: null
  value: Not Set
_wandb:
  desc: null
  value:
    cli_version: 0.8.12
    is_jupyter_run: false
    python_version: 3.6.8
batch_size:
  desc: null
  value: 1000
code_mark_subtoken_end:
  desc: null
  value: true
code_max_num_tokens:
  desc: null
  value: 200
code_pct_bpe:
  desc: null
  value: 0.5
code_rnn_cell_type:
  desc: null
  value: LSTM
code_rnn_dropout_keep_rate:
  desc: null
  value: 0.8
code_rnn_hidden_dim:
  desc: null
  value: 64
code_rnn_is_bidirectional:
  desc: null
  value: true
code_rnn_num_layers:
  desc: null
  value: 2
code_rnn_pool_mode:
  desc: null
  value: weighted_mean
code_rnn_recurrent_dropout_keep_rate:
  desc: null
  value: 1.0
code_token_embedding_size:
  desc: null
  value: 128
code_token_vocab_count_threshold:
  desc: null
  value: 10
code_token_vocab_size:
  desc: null
  value: 10000
code_use_bpe:
  desc: null
  value: true
code_use_subtokens:
  desc: null
  value: false
dropout_keep_rate:
  desc: null
  value: 0.9
fraction_using_func_name:
  desc: null
  value: 0.1
gradient_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
learning_rate_code_scale_factor:
  desc: null
  value: 1.0
learning_rate_decay:
  desc: null
  value: 0.98
learning_rate_query_scale_factor:
  desc: null
  value: 1.0
loss:
  desc: null
  value: softmax
margin:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 300
min_len_func_name_for_query:
  desc: null
  value: 12
model-class:
  desc: null
  value: rnn
momentum:
  desc: null
  value: 0.85
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
query_mark_subtoken_end:
  desc: null
  value: false
query_max_num_tokens:
  desc: null
  value: 30
query_pct_bpe:
  desc: null
  value: 0.5
query_random_token_frequency:
  desc: null
  value: 0.0
query_rnn_cell_type:
  desc: null
  value: LSTM
query_rnn_dropout_keep_rate:
  desc: null
  value: 0.8
query_rnn_hidden_dim:
  desc: null
  value: 64
query_rnn_is_bidirectional:
  desc: null
  value: true
query_rnn_num_layers:
  desc: null
  value: 2
query_rnn_pool_mode:
  desc: null
  value: weighted_mean
query_rnn_recurrent_dropout_keep_rate:
  desc: null
  value: 1.0
query_token_embedding_size:
  desc: null
  value: 128
query_token_vocab_count_threshold:
  desc: null
  value: 10
query_token_vocab_size:
  desc: null
  value: 10000
query_use_bpe:
  desc: null
  value: true
query_use_subtokens:
  desc: null
  value: false
run-name:
  desc: null
  value: null
save_folder:
  desc: null
  value: /home/dev/resources/saved_models
seed:
  desc: null
  value: 0
test_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/test]'
train_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/train]'
valid_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/valid]'
